language: ruby

rvm:
  - 3.0.0

services:
  - postgresql

addons:
  chrome: stable

env:
  global:
    CC_TEST_REPORTER_ID=4909ecb65071cda05313bb6560b1f39225430c596cfe879f19e3ca473d815d6d

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - npm i -g yarn
  - yarn install

before_script:
  - bundle exec rails db:create db:migrate RAILS_ENV=test
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rails webpacker:compile
  - bundle exec rspec
  - yarn test

after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/.resultset.json
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json coverage/lcov.info
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
